# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MyConnection'
    subscriptionId: 'b0a62e67-fe11-4a84-b57d-860652f00af3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG-APIM-Default'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'apiserviceml4q4yys6uch2-apis.template.json'
    deploymentMode: 'Validation'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '.\*.json'
    azureSubscription: 'MyConnection'
    Destination: 'AzureBlob'
    storage: 'dvdldeployment'
    ContainerName: 'logicapp'