POST https://prod-45.westeurope.logic.azure.com:443/workflows/2853068befa14c2ebf4591724460b4c4/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=obUm918A61tFNVBANWlBjE0-0A7C6VIemuYsMtRX_3s
Content-Type: application/json

{
    "Person":
    {
        "Firstname": "This ",
        "Lastname": "is Acceptance"
    }
}

POST https://prod-140.westeurope.logic.azure.com:443/workflows/9ddd5d1c6a7c4b769b4669a8b45b00b4/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=VTHuzJf0r4g7qAs8MS30NtRZS2unT-t0UT_w35ZnKzU
Content-Type: application/json

{
    "Person":
    {
        "Firstname": "This ",
        "Lastname": "is Test"
    }
}