POST https://prod-151.westeurope.logic.azure.com:443/workflows/c44a8a1afcea4974b887cbc1a8937185/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=kFuaqRItvmK3VDbDYS4ok2whFbV1-CTkOc2fxftHfaY
Content-Type: application/json

{
    "Person":
    {
        "Firstname": "This ",
        "Lastname": "is Acceptance"
    }
}

POST https://prod-160.westeurope.logic.azure.com:443/workflows/708a95f2f5f14a2295e14b75a6ba681d/triggers/manual/paths/invoke?api-version=2019-05-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=2NuMNF5XWD927CxOmLeJFgkgAtGCkNbKcJNvIa8CA00
Content-Type: application/json

{
    "Person":
    {
        "Firstname": "This ",
        "Lastname": "is Test"
    }
}

PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/subscriptions/{sid}?api-version=2019-12-01